name: spaghettiserver
description: Simple file bin service
version: 0.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  path: ^1.8.3
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4
  universal_disk_space: ^0.2.3
  # path: ^1.8.0
  filesize: ^2.0.1
  args: ^2.4.2
dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
